'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TX_Text_Control_Words.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property APP_MENU_EXIT() As String
            Get
                Return ResourceManager.GetString("APP_MENU_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close the Program.
        '''</summary>
        Friend ReadOnly Property APP_MENU_EXIT_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_EXIT_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend ReadOnly Property APP_MENU_NEW() As String
            Get
                Return ResourceManager.GetString("APP_MENU_NEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Document.
        '''</summary>
        Friend ReadOnly Property APP_MENU_NEW_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_NEW_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open….
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Sample Template.
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN_SAMPLE() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN_SAMPLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load a Sample Invoice..
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN_SAMPLE_INVOICE() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN_SAMPLE_INVOICE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load a Sample Packing List..
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN_SAMPLE_PACK_LST() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN_SAMPLE_PACK_LST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load a Sample Shipping Label..
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN_SAMPLE_SHIP_LBL() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN_SAMPLE_SHIP_LBL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open a sample template document..
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN_SAMPLE_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN_SAMPLE_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Document.
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPEN_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPEN_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options….
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPTIONS() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPTIONS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show the Options Dialog.
        '''</summary>
        Friend ReadOnly Property APP_MENU_OPTIONS_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_OPTIONS_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print….
        '''</summary>
        Friend ReadOnly Property APP_MENU_PRINT() As String
            Get
                Return ResourceManager.GetString("APP_MENU_PRINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Preview….
        '''</summary>
        Friend ReadOnly Property APP_MENU_PRINT_PREVIEW() As String
            Get
                Return ResourceManager.GetString("APP_MENU_PRINT_PREVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quick Print.
        '''</summary>
        Friend ReadOnly Property APP_MENU_PRINT_QUICK() As String
            Get
                Return ResourceManager.GetString("APP_MENU_PRINT_QUICK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send the document directly to the default printer without making any changes..
        '''</summary>
        Friend ReadOnly Property APP_MENU_PRINT_QUICK_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_PRINT_QUICK_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a printer, number of copies and other printing options before printing..
        '''</summary>
        Friend ReadOnly Property APP_MENU_PRINT_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_PRINT_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recent Items.
        '''</summary>
        Friend ReadOnly Property APP_MENU_RECENT_ITEMS_HEADER() As String
            Get
                Return ResourceManager.GetString("APP_MENU_RECENT_ITEMS_HEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save As….
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Word 97 - 2003 Document (*.doc).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_DOC() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_DOC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a copy of the document that is fully compatible with Microsoft Word 97 – 2003..
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_DOC_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_DOC_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Word Document (*.docx).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_DOCX() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_DOCX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a copy of the document in the DOCX-Format..
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_DOCX_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_DOCX_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hypertext Markup Language (*.html, *.html).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_HTML() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_HTML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a copy of the document as a web page..
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_HTML_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_HTML_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Formats.
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_OTHER() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_OTHER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open the save as dialog box to select from all possible file formats..
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_OTHER_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_OTHER_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adobe PDF document (*.pdf).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_PDF() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_PDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a copy of the document in the Adobe Portable Document Format..
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_PDF_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_PDF_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rich Text Format (*.rtf).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_RTF() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_RTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save a copy of the document in the Rich Text Format..
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_RTF_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_RTF_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Document As….
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internal Unicode Format (*.tx).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_TX() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_TX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plain Text Document (*.txt).
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_AS_TXT() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_AS_TXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Document.
        '''</summary>
        Friend ReadOnly Property APP_MENU_SAVE_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("APP_MENU_SAVE_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please click here to get started with TX Text Control WPF..
        '''</summary>
        Friend ReadOnly Property APP_MENU_TOOLTIP_DESC() As String
            Get
                Return ResourceManager.GetString("APP_MENU_TOOLTIP_DESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TX Text Control Application Menu.
        '''</summary>
        Friend ReadOnly Property APP_MENU_TOOLTIP_TITLE() As String
            Get
                Return ResourceManager.GetString("APP_MENU_TOOLTIP_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Cancel.
        '''</summary>
        Friend ReadOnly Property BTN_CANCEL() As String
            Get
                Return ResourceManager.GetString("BTN_CANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Preview.
        '''</summary>
        Friend ReadOnly Property BTN_CLOSE_PREVIEW() As String
            Get
                Return ResourceManager.GetString("BTN_CLOSE_PREVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closes the preview..
        '''</summary>
        Friend ReadOnly Property BTN_CLOSE_PREVIEW_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_CLOSE_PREVIEW_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finish &amp; Merge.
        '''</summary>
        Friend ReadOnly Property BTN_FINISH_AND_MERGE() As String
            Get
                Return ResourceManager.GetString("BTN_FINISH_AND_MERGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge data into the current document..
        '''</summary>
        Friend ReadOnly Property BTN_FINISH_AND_MERGE_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_FINISH_AND_MERGE_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Record.
        '''</summary>
        Friend ReadOnly Property BTN_FIRST_RECORD() As String
            Get
                Return ResourceManager.GetString("BTN_FIRST_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chart.
        '''</summary>
        Friend ReadOnly Property BTN_INSERT_CHART() As String
            Get
                Return ResourceManager.GetString("BTN_INSERT_CHART", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Record.
        '''</summary>
        Friend ReadOnly Property BTN_LAST_RECORD() As String
            Get
                Return ResourceManager.GetString("BTN_LAST_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left to Right.
        '''</summary>
        Friend ReadOnly Property BTN_LTR() As String
            Get
                Return ResourceManager.GetString("BTN_LTR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge into Current Document.
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_CURRENT() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_CURRENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create multiple {0} files..
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_INDIV_X_FILES_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_INDIV_X_FILES_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge into Individual Documents.
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_MULTIPLE_FILES() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_MULTIPLE_FILES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge data into separate files..
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_MULTIPLE_FILES_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_MULTIPLE_FILES_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge into Single File.
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_SINGLE_FILE() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_SINGLE_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge data into a single file..
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_SINGLE_FILE_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_SINGLE_FILE_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge data into a single {0} file..
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_INTO_SINGLE_X_FILE_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_INTO_SINGLE_X_FILE_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Document.
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_PRINT() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_PRINT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge data and print the result..
        '''</summary>
        Friend ReadOnly Property BTN_MERGE_PRINT_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_MERGE_PRINT_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next Record.
        '''</summary>
        Friend ReadOnly Property BTN_NEXT_RECORD() As String
            Get
                Return ResourceManager.GetString("BTN_NEXT_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;OK.
        '''</summary>
        Friend ReadOnly Property BTN_OK() As String
            Get
                Return ResourceManager.GetString("BTN_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview.
        '''</summary>
        Friend ReadOnly Property BTN_PREVIEW() As String
            Get
                Return ResourceManager.GetString("BTN_PREVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge data from the datasource into merge fields and merge blocks to see how the finished document will look..
        '''</summary>
        Friend ReadOnly Property BTN_PREVIEW_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("BTN_PREVIEW_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Previous Record.
        '''</summary>
        Friend ReadOnly Property BTN_PREVIOUS_RECORD() As String
            Get
                Return ResourceManager.GetString("BTN_PREVIOUS_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Redo.
        '''</summary>
        Friend ReadOnly Property BTN_REDO() As String
            Get
                Return ResourceManager.GetString("BTN_REDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right to Left.
        '''</summary>
        Friend ReadOnly Property BTN_RTL() As String
            Get
                Return ResourceManager.GetString("BTN_RTL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Undo.
        '''</summary>
        Friend ReadOnly Property BTN_UNDO() As String
            Get
                Return ResourceManager.GetString("BTN_UNDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chart Data.
        '''</summary>
        Friend ReadOnly Property CHART_DATA_GRID_DLG_TITLE() As String
            Get
                Return ResourceManager.GetString("CHART_DATA_GRID_DLG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frame Tools.
        '''</summary>
        Friend ReadOnly Property CONT_TAB_GRP_FRAME_TOOLS() As String
            Get
                Return ResourceManager.GetString("CONT_TAB_GRP_FRAME_TOOLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Table Tools.
        '''</summary>
        Friend ReadOnly Property CONT_TAB_GRP_TBL_TOOLS() As String
            Get
                Return ResourceManager.GetString("CONT_TAB_GRP_TBL_TOOLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Chart Properties….
        '''</summary>
        Friend ReadOnly Property CONTEXTMENU_CHART_PROPS() As String
            Get
                Return ResourceManager.GetString("CONTEXTMENU_CHART_PROPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit Chart Data….
        '''</summary>
        Friend ReadOnly Property CONTEXTMENU_EDIT_CHART_DATA() As String
            Get
                Return ResourceManager.GetString("CONTEXTMENU_EDIT_CHART_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Set Chart Data Relation….
        '''</summary>
        Friend ReadOnly Property CONTEXTMENU_SET_CHART_DATA_REL() As String
            Get
                Return ResourceManager.GetString("CONTEXTMENU_SET_CHART_DATA_REL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reporting.
        '''</summary>
        Friend ReadOnly Property CONTEXTUAL_TAB_GROUP_REPORTING() As String
            Get
                Return ResourceManager.GetString("CONTEXTUAL_TAB_GROUP_REPORTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [untitled].
        '''</summary>
        Friend ReadOnly Property DOC_TITLE_UNTITLED() As String
            Get
                Return ResourceManager.GetString("DOC_TITLE_UNTITLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You need at least the Professional version to use this feature..
        '''</summary>
        Friend ReadOnly Property EXC_LICENSE_PRO() As String
            Get
                Return ResourceManager.GetString("EXC_LICENSE_PRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TX Text Control Reports:
        '''The following merge blocks could not be converted:
        '''{0}
        '''
        '''Remove the corresponding bookmarks with:
        '''Insert - Bookmark - Delete Bookmark.
        '''Create a new block with:
        '''Reporting - Insert Merge Block - Insert Custom Merge Block..
        '''</summary>
        Friend ReadOnly Property EXC_MERGE_BLOCK_CONVERSION() As String
            Get
                Return ResourceManager.GetString("EXC_MERGE_BLOCK_CONVERSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Block name must not be null or empty..
        '''</summary>
        Friend ReadOnly Property EXC_MERGEBLOCK_EMPTY_BLOCK_NAME() As String
            Get
                Return ResourceManager.GetString("EXC_MERGEBLOCK_EMPTY_BLOCK_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only absolute file paths / links are supported..
        '''</summary>
        Friend ReadOnly Property EXC_ONLY_ABS_PATH_SUPORTED() As String
            Get
                Return ResourceManager.GetString("EXC_ONLY_ABS_PATH_SUPORTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There seems to be a problem with the PDF signature file settings: {0}.
        '''</summary>
        Friend ReadOnly Property EXC_PDF_SIGNATURE() As String
            Get
                Return ResourceManager.GetString("EXC_PDF_SIGNATURE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Properties….
        '''</summary>
        Friend ReadOnly Property FIELD_NAV_BTN_PROPERTIES() As String
            Get
                Return ResourceManager.GetString("FIELD_NAV_BTN_PROPERTIES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete.
        '''</summary>
        Friend ReadOnly Property FIELD_NAV_BTN_REMOVE() As String
            Get
                Return ResourceManager.GetString("FIELD_NAV_BTN_REMOVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field Navigation.
        '''</summary>
        Friend ReadOnly Property FIELD_NAV_LBL_HEADER() As String
            Get
                Return ResourceManager.GetString("FIELD_NAV_LBL_HEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Template.
        '''</summary>
        Friend ReadOnly Property FIELD_NAV_SEARCH_TEXT_PLACEHOLDER() As String
            Get
                Return ResourceManager.GetString("FIELD_NAV_SEARCH_TEXT_PLACEHOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to merge blocks.
        '''</summary>
        Friend ReadOnly Property FIELD_NAV_TAB_MERGE_BLOCKS() As String
            Get
                Return ResourceManager.GetString("FIELD_NAV_TAB_MERGE_BLOCKS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to merge fields.
        '''</summary>
        Friend ReadOnly Property FIELD_NAV_TAB_MERGE_FIELDS() As String
            Get
                Return ResourceManager.GetString("FIELD_NAV_TAB_MERGE_FIELDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge block is not empty. Delete all contained fields and nested blocks before removing the block..
        '''</summary>
        Friend ReadOnly Property FIELDNAV_DLG_MERGE_BLOCK_NOT_EMPTY() As String
            Get
                Return ResourceManager.GetString("FIELDNAV_DLG_MERGE_BLOCK_NOT_EMPTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Go to record no. {0}..
        '''</summary>
        Friend ReadOnly Property GO_TO_RECORD_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("GO_TO_RECORD_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property LIMIT_PREVIEW_DATA_DLG_CANCEL() As String
            Get
                Return ResourceManager.GetString("LIMIT_PREVIEW_DATA_DLG_CANCEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property LIMIT_PREVIEW_DATA_DLG_OK() As String
            Get
                Return ResourceManager.GetString("LIMIT_PREVIEW_DATA_DLG_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of preview results.
        '''</summary>
        Friend ReadOnly Property LIMIT_PREVIEW_DATA_DLG_TEXT() As String
            Get
                Return ResourceManager.GetString("LIMIT_PREVIEW_DATA_DLG_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Limit Preview Data.
        '''</summary>
        Friend ReadOnly Property LIMIT_PREVIEW_DATA_DLG_TITLE() As String
            Get
                Return ResourceManager.GetString("LIMIT_PREVIEW_DATA_DLG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No merge results were created. Aborting..
        '''</summary>
        Friend ReadOnly Property MERGE_NO_MERGE_RESULTS() As String
            Get
                Return ResourceManager.GetString("MERGE_NO_MERGE_RESULTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merging….
        '''</summary>
        Friend ReadOnly Property MERGE_WAIT_DLG_LBL_MERGING() As String
            Get
                Return ResourceManager.GetString("MERGE_WAIT_DLG_LBL_MERGING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Wait.
        '''</summary>
        Friend ReadOnly Property MERGE_WAIT_DLG_TITLE() As String
            Get
                Return ResourceManager.GetString("MERGE_WAIT_DLG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Reporting Template was stored in an older TX Text Control format.
        '''Do you want to save it in the current format?.
        '''</summary>
        Friend ReadOnly Property MSG_CONFIRM_UPDATE_MERGE_BLOCK_TYPE() As String
            Get
                Return ResourceManager.GetString("MSG_CONFIRM_UPDATE_MERGE_BLOCK_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not open link / file path..
        '''</summary>
        Friend ReadOnly Property MSG_COULD_NOT_OPEN_LINK() As String
            Get
                Return ResourceManager.GetString("MSG_COULD_NOT_OPEN_LINK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File &quot;{0}&quot; does not exist..
        '''</summary>
        Friend ReadOnly Property MSG_FILE_DOES_NOT_EXIST() As String
            Get
                Return ResourceManager.GetString("MSG_FILE_DOES_NOT_EXIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file does not exist. Do you want 
        '''to remove it from the list of recent files?.
        '''</summary>
        Friend ReadOnly Property MSG_REMOVE_FILE_FROM_LIST() As String
            Get
                Return ResourceManager.GetString("MSG_REMOVE_FILE_FROM_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown file type (*{0})..
        '''</summary>
        Friend ReadOnly Property MSG_UNKNOWN_FILE_TYPE() As String
            Get
                Return ResourceManager.GetString("MSG_UNKNOWN_FILE_TYPE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Sample Database.
        '''</summary>
        Friend ReadOnly Property OPEN_SAMPLE_DB_MENU_BTN_TEXT() As String
            Get
                Return ResourceManager.GetString("OPEN_SAMPLE_DB_MENU_BTN_TEXT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load a sample database..
        '''</summary>
        Friend ReadOnly Property OPEN_SAMPLE_DB_MENU_BTN_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("OPEN_SAMPLE_DB_MENU_BTN_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HTML stylesheet save options.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_CSS_GRP_SAVEOPTS() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_CSS_GRP_SAVEOPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Inline stylesheet.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_CSS_INLINE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_CSS_INLINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylesheet file:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_CSS_LBL_FILE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_CSS_LBL_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;No stylesheet.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_CSS_NONE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_CSS_NONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sa&amp;ve but do not overwrite existing file.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_CSS_SAVE_NOT_OVR() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_CSS_SAVE_NOT_OVR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Save stylesheet in separate file.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_CSS_SEPARATE_FILE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_CSS_SEPARATE_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Enable PDF/A.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFEXP_ENABLE_PDFA() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFEXP_ENABLE_PDFA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Export Options.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFEXP_GRP_OPTS() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFEXP_GRP_OPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Import Options.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFIMP_GRP_OPTS() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFIMP_GRP_OPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import mode:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFIMP_LBL_MODE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFIMP_LBL_MODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text frame import mode.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFIMP_MODE_FRAMES() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFIMP_MODE_FRAMES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paragraph recognition mode.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFIMP_MODE_PAR() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFIMP_MODE_PAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plain text mode.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFIMP_MODE_PLAIN() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFIMP_MODE_PLAIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable text access for screen reader devices for the &amp;visually impaired.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_ALLOW_ACCESSIBILITY() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_ALLOW_ACCESSIBILITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Enable copying of text, images, and other content.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_ALLOW_EXTR_CNT() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_ALLOW_EXTR_CNT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Any except extracting pages.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_CHNGALLOW_ANY() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_CHNGALLOW_ANY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commenting, filling in form fields and signing.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_CHNGALLOW_COMMENTS() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_CHNGALLOW_COMMENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filling in form fields and signing.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_CHNGALLOW_FORMFLDS() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_CHNGALLOW_FORMFLDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inserting, deleting and rotating pages.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_CHNGALLOW_INSDEL() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_CHNGALLOW_INSDEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_CHNGALLOW_NONE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_CHNGALLOW_NONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The &apos;Require a password to open the document&apos; option is 
        '''selected, but the Document Open Password field is empty.
        '''Please enter a password or deselect the security option..
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_ERR_NO_DOC_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_ERR_NO_DOC_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The &apos;Use a password to restrict printing and editing of the 
        '''document and its security settings&apos; option is selected, but 
        '''the Permissions Password field is empty. Please enter a 
        '''password or deselect the security option..
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_ERR_NO_MASTER_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_ERR_NO_MASTER_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Document Open and Permissions passwords cannot
        '''be the same. Please enter a different password in either the 
        '''Document Open Password field or the Permission Password 
        '''field..
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_ERR_SAME_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_ERR_SAME_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Digital Signature.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_GRP_DIG_SIG() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_GRP_DIG_SIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Document Password.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_GRP_DOC_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_GRP_DOC_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permissions.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_GRP_PERM() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_GRP_PERM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes &amp;Allowed:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_LBL_ALLOW_CHNG() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_LBL_ALLOW_CHNG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pri&amp;nting Allowed:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_LBL_ALLOW_PRNT() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_LBL_ALLOW_PRNT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Certificate File (*.pfx):.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_LBL_CERT_FILE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_LBL_CERT_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Certificate &amp;Password:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_LBL_CERT_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_LBL_CERT_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Document Password:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_LBL_DOC_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_LBL_DOC_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Permissions Password:.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_LBL_PERM_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_LBL_PERM_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to High Resolution.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_PRNTMODE_HIRES() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_PRNTMODE_HIRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Low Resolution.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_PRNTMODE_LOWRES() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_PRNTMODE_LOWRES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_PRNTMODE_NONE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_PRNTMODE_NONE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Require a password to open the document.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_REQ_DOC_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_REQ_DOC_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Require Password for restricting printing and editing of the document.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_PDFSEC_REQ_MSTR_PWD() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_PDFSEC_REQ_MSTR_PWD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HTML Options.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_TAB_HTMLOPTS() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_TAB_HTMLOPTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Export.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_TAB_PDFEXP() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_TAB_PDFEXP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Import.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_TAB_PDFIMP() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_TAB_PDFIMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PDF Security.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_TAB_PDFSEC() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_TAB_PDFSEC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend ReadOnly Property OPT_DLG_TITLE() As String
            Get
                Return ResourceManager.GetString("OPT_DLG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finish.
        '''</summary>
        Friend ReadOnly Property RIBBON_GROUP_FINISH() As String
            Get
                Return ResourceManager.GetString("RIBBON_GROUP_FINISH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigate.
        '''</summary>
        Friend ReadOnly Property RIBBON_GROUP_NAVIGATE() As String
            Get
                Return ResourceManager.GetString("RIBBON_GROUP_NAVIGATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview.
        '''</summary>
        Friend ReadOnly Property RIBBON_GROUP_PREVIEW() As String
            Get
                Return ResourceManager.GetString("RIBBON_GROUP_PREVIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frame Formatting.
        '''</summary>
        Friend ReadOnly Property RIBBON_TAB_FRAME_FORMAT_HEADER() As String
            Get
                Return ResourceManager.GetString("RIBBON_TAB_FRAME_FORMAT_HEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   Preview  .
        '''</summary>
        Friend ReadOnly Property RIBBON_TAB_PREVIEW_HEADER() As String
            Get
                Return ResourceManager.GetString("RIBBON_TAB_PREVIEW_HEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Table Formatting.
        '''</summary>
        Friend ReadOnly Property RIBBON_TAB_TABLE_FORMAT_HEADER() As String
            Get
                Return ResourceManager.GetString("RIBBON_TAB_TABLE_FORMAT_HEADER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes to {0}?.
        '''</summary>
        Friend ReadOnly Property SAVE_CHANGES_TO() As String
            Get
                Return ResourceManager.GetString("SAVE_CHANGES_TO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column: .
        '''</summary>
        Friend ReadOnly Property STATUSBAR_COLUMN() As String
            Get
                Return ResourceManager.GetString("STATUSBAR_COLUMN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line: .
        '''</summary>
        Friend ReadOnly Property STATUSBAR_LINE() As String
            Get
                Return ResourceManager.GetString("STATUSBAR_LINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page: .
        '''</summary>
        Friend ReadOnly Property STATUSBAR_PAGE() As String
            Get
                Return ResourceManager.GetString("STATUSBAR_PAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Section: .
        '''</summary>
        Friend ReadOnly Property STATUSBAR_SECTION() As String
            Get
                Return ResourceManager.GetString("STATUSBAR_SECTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Field Navigation.
        '''</summary>
        Friend ReadOnly Property TGL_BTN_FIELD_NAVIGATION() As String
            Get
                Return ResourceManager.GetString("TGL_BTN_FIELD_NAVIGATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows or hides the Field Navigator panel..
        '''</summary>
        Friend ReadOnly Property TGL_BTN_FIELD_NAVIGATION_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("TGL_BTN_FIELD_NAVIGATION_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter the master password or press cancel
        '''to open the document in restricted mode:.
        '''</summary>
        Friend ReadOnly Property USR_INP_MASTER_PASSWORD_LABEL() As String
            Get
                Return ResourceManager.GetString("USR_INP_MASTER_PASSWORD_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Master Password.
        '''</summary>
        Friend ReadOnly Property USR_INP_MASTER_PASSWORD_TITLE() As String
            Get
                Return ResourceManager.GetString("USR_INP_MASTER_PASSWORD_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Merge block name:.
        '''</summary>
        Friend ReadOnly Property USR_INP_MERGE_BLOCK_NAME_LABEL() As String
            Get
                Return ResourceManager.GetString("USR_INP_MERGE_BLOCK_NAME_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rename Merge Block.
        '''</summary>
        Friend ReadOnly Property USR_INP_MERGE_BLOCK_NAME_TITLE() As String
            Get
                Return ResourceManager.GetString("USR_INP_MERGE_BLOCK_NAME_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter password for password protected file:.
        '''</summary>
        Friend ReadOnly Property USR_INP_PASSWORD_LABEL() As String
            Get
                Return ResourceManager.GetString("USR_INP_PASSWORD_LABEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter Password.
        '''</summary>
        Friend ReadOnly Property USR_INP_PASSWORD_TITLE() As String
            Get
                Return ResourceManager.GetString("USR_INP_PASSWORD_TITLE", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
